# Generated by Django 2.2 on 2020-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.TextField()),
                ('especificaciones', models.TextField()),
                ('precioTotal', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField()),
            ],
        ),
    ]
