# Generated by Django 3.0.5 on 2020-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField()),
            ],
        ),
    ]
