# Generated by Django 2.2 on 2020-04-20 02:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200419_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='receta',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
