# Generated by Django 2.2 on 2020-04-20 03:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20200419_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='receta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
