# Generated by Django 2.2 on 2020-04-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ing', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaIngredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('ingred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.Ingrediente')),
                ('pdeido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Pedido')),
            ],
        ),
    ]
